version: "3.3"
services:
  redis:
    image: redis
    container_name: redis-fluency
    ports:
      - "6379:6379"
    restart: always
  # redis:
  #   image: redislabs/rebloom:latest
  #   container_name: redis-fluency
  #   ports:
  #     - "6379:6379"
  #   restart: always
